on:
  push:
    branches:
      - main
jobs:
  buld:
    runs-on: ubuntu-latest
    steps:
    - name: bicep-build-output
      uses: Azure/bicep-build-action@v1.0.1
      with:
        bicepFilePath: .github/workflows/staticweb.bicep
        outputFilePath: .github/workflows/azuredeploy.json
          
